# Generated by Django 4.2.6 on 2023-10-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_imagemessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagemessage",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="imagemessage",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
