# Generated by Django 4.2.6 on 2023-10-28 05:29

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_imagemessage_options_imagemessage_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemessage",
            name="image",
            field=models.ImageField(
                upload_to=base.models.ImageMessage.unique_image_filename
            ),
        ),
    ]
