# Generated by Django 4.2.6 on 2023-10-28 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_pdfmessage_pdf_file_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterField(
            model_name="status",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
