# Generated by Django 4.2.6 on 2023-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_status_options_alter_status_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
