# Generated by Django 4.2.6 on 2023-10-28 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_status_liked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="liked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
