# Generated by Django 4.2.6 on 2023-10-30 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_status_liked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="liked_by",
        ),
        migrations.AddField(
            model_name="status",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_statuses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
